name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          start: npm start
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6
      - name: Setup Node env 🏗
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install dependencies 👨🏻‍💻
        run: npm ci
      - name: Run linter 👀
        run: npm run lint:check
